[package]
name = "skald"
version = "0.1.0"
edition = "2021"
description = "Embeddable garbage-collected bytecode scripting engine"
license = "MIT"

[lib]
name = "skald"
path = "src/lib.rs"

[[bin]]
name = "skald"
path = "src/bin/skald.rs"

[dependencies]

[dev-dependencies]

[profile.release]
debug = true
