[package]
name = "fwctl-sim"
description = "Firmware update device simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fwctl-core = { path = "../fwctl-core" }
fwctl-device = { path = "../fwctl-device" }
thiserror.workspace = true

[dev-dependencies]
sha2.workspace = true

[lints]
workspace = true
